### ISSUE TITLE
font-family is missing

### ISSUE THREAD

**Issue by sshojiro** [utttime/utttime.github.io#20]
Font-family such as "Meiryo" should be defined in dinky-ttweb.scss. 
The final font should be determined after discussion. 

<img width="417" alt="Screenshot_2020_06_08_13_28" src="https://user-images.githubusercontent.com/2136270/83992671-0acdda80-a98c-11ea-9c43-152eb8e6504a.png">

**Comment by m12watanabe1a** [comment]
Noto Sans JP
https://fonts.google.com/specimen/Noto+Sans+JP?subset=japanese#license
